//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSchedule
    {
        public int ExamScheduleID { get; set; }
        public string ClassId { get; set; }
        public string SubjectID { get; set; }
        public System.DateTime Examday { get; set; }
        public System.TimeSpan TimeIn { get; set; }
        public System.TimeSpan TimeOut { get; set; }
        public string Note { get; set; }
        public int RoomID { get; set; }
        public bool status { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Room Room { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
