//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelParentStudent
    {
        public int Id { get; set; }
        public int ParentID { get; set; }
        public string StudentID { get; set; }
        public string RelationWithStudent { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual Student Student { get; set; }
    }
}
