//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.ClassMembers = new HashSet<ClassMember>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Grades = new HashSet<Grade>();
            this.RelParentStudents = new HashSet<RelParentStudent>();
        }

        [Required(ErrorMessage = "The StudentId field is required")]

        public string StudentID { get; set; }
        [Required(ErrorMessage = "The Student name field is required")]

        public string StudentName { get; set; }
        [Required(ErrorMessage = "The Phone field is required")]

        public string Phone { get; set; }
        [Required(ErrorMessage = "Address field is required")]

        public string Address { get; set; }
        [Required(ErrorMessage = "The Gender field is required")]

        public bool Gender { get; set; }
        [Required(ErrorMessage = "The Password field is required")]

        public string Password { get; set; }
        [Required(ErrorMessage = "The Email field is required")]

        public string Email { get; set; }
        [Required(ErrorMessage = "The Image field is required")]

        public string Image { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Birthday { get; set; }
        public bool Status { get; set; }
        public string Educationlevel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMember> ClassMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelParentStudent> RelParentStudents { get; set; }
    }
}
